{% set name = "perl-dbi" %}
{% set version = "1.647" %}
{% set sha256 = "0df16af8e5b3225a68b7b592ab531004ddb35a9682b50300ce50174ad867d9aa" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/H/HM/HMBRAND/DBI-{{ version }}.tgz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make -j"${CPU_COUNT}"
    - make test   # [build_platform == target_platform]
    - make install VERBINST=1

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-test-simple
  run:
    - perl

test:
  imports:
    - DBI

about:
  home: "https://metacpan.org/pod/DBI"
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: "Database independent interface for Perl."
  license_file: LICENSE
  doc_url: "https://metacpan.org/pod/DBI"

extra:
  recipe-maintainers:
    - conda-forge/perl-packagers
